### ISSUE TITLE
Global Variable is not saved properly on reload

### ISSUE THREAD

**Issue by wysohn** [TriggerReactor/TriggerReactor#161]
Maybe the reload part is not synchronized with saving thread

**Comment by wysohn** [comment]
It seems the reload command load the file before the contents in the memory are written to the file causing corruption

Reload command must wait until previous save task is done

**Comment by rkdrns4747** [comment]
This problem is still on-going in 3.0.4, and I found this happens only when we try to save null (to delete it).

**Comment by wysohn** [comment]
Interesting will look into it

Do you have specific steps to reproduce the problem?

**Comment by wysohn** [comment]
@rkdrns4747 
Please re-open with the steps required to reproduce the problem.

Can't really pin-point the problem at the moment.
