### ISSUE TITLE
config file rework

### ISSUE THREAD

**Issue by wysohn** [TriggerReactor/TriggerReactor#167]
Need to create a unified config file that can be used in both spigot and sponge.

and add useInGameEditor option

**Comment by MidnightSugar** [comment]
Also config to change trigger items. Like bone in case of conflicts.

**Comment by wysohn** [comment]
### Design Proposal
---
![Config](https://user-images.githubusercontent.com/8789836/71563688-aa378a80-2a48-11ea-82f9-2834cd599f97.jpg)

`String key` can contain a dot(.) to indicate the hierarchy just like how FileConfiguration works. The only difference is that we are going to include Gson library as part of our project and do not rely on either Bukkit API or Sponge API.

ConfigManager may be reused inside various other Trigger related Managers (it can be helpful to unify the file handling logics in the abstraction layer instead of handling them separately using different APIs), but it's not necessary.

This will be helpful to solve #241 and help us adding more options for users.

@gerzytet @rkdrns4747

**Comment by wysohn** [comment]
### Migration and Config Loading Flow
---
![Config Rework](https://user-images.githubusercontent.com/8789836/72016906-811db380-3219-11ea-9969-061a02aec962.jpg)

**Comment by wysohn** [comment]
#254
