### ISSUE TITLE
Add Switch&Case

### ISSUE THREAD

**Issue by rkdrns4747** [TriggerReactor/TriggerReactor#186]
We have IF statement rn, but It's not enough to handle  conditioning all situations. I think It's better to add new operator, SWITCH, CASE, which do the  same thing as switch(){ case: } in Java.

It could be LongRun, or might not be.

**Comment by gerzytet** [comment]
Switch-case doesn’t allow anything that if-statements don’t already do, and it will add more complexity to the language, so I doubt this is worth implementing.  In any case, it should be a low priority.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rkdrns4747** [comment]
@gerzytet 
I added this issue bcz more than 10 of developers suggested this. It could be more complex in scripting or viewing scripts, but I feel confident about adding more operators, SWITCH CASE.
