### ISSUE TITLE
Add an Executor for handling NMS(Packet)

### ISSUE THREAD

**Issue by rkdrns4747** [TriggerReactor/TriggerReactor#247]
Trigger Reactor is great plugin for people who want to make simple system without making plugin. However, It is hard to handle NMS(such as Packet) on scripting in TR.

So, It will be really comfortable and highly improve TR's implemention ability to add an Executor named `#PACKET`, which make user able to send a packet.

**Comment by gerzytet** [comment]
@rkdrns4747 
how would you use it?
also, you should consider making #PACKET use protocollib, as it already has lots of utilities for handling packets, and most servers have it installed anyway as a dependency.

**Comment by rkdrns4747** [comment]
this issue will be handled after whole projects being refactored.
