### ISSUE TITLE
#SETGAMEMODE has error itself on js file

### ISSUE THREAD

**Issue by rkdrns4747** [TriggerReactor/TriggerReactor#257]

**Comment by gerzytet** [comment]
Commit it to master, so it will be released for 3.0.2.

**Comment by rkdrns4747** [comment]
@gerzytet 
Actually 3.0.2 was released already, this may released on 3.0.3 or 3.1.0.
I'll commit it to master though.

**Comment by gerzytet** [comment]
Yeah, I meant 3.0.3
