### ISSUE TITLE
org.bukkit.event.entity.EntityDamageEvent not hooked?

### ISSUE THREAD

**Issue by chickiyeah** [TriggerReactor/TriggerReactor#262]
org.bukkit.event.entity.EntityDamageEvent
org.bukkit.event.entity.EntityDamageByEntityEvent
both sync and no sync are unresponsive

**Comment by wysohn** [comment]
Can you give us some more details?

Do you see any error messages?

What version of Spigot/Bukkit/Paper are you using?

What version of TriggerReactor are you using?

Can you share the code to reproduce the problem if possible?

**Comment by chickiyeah** [comment]
Just no response
Not ErrorMessage
SPIGOT
3.0.2
#MESSAGE "is,it run?"
