### ISSUE TITLE
Nodejs

### ISSUE THREAD

**Issue by Madur23** [TriggerReactor/TriggerReactor#278]
### **Before/읽어주세요**

Make sure that you have used `/trg debug` so that the more detailed error message will show up in the console.
신고전에 `/trg debug` 명령어를 사용해서 디버그 모드를 켜주세요. 그래야 콘솔창에 더 자세한 정보가 나옵니다.

---

**Describe the bug/버그 증상**
어떤 증상이 발상하는지 작성 해 주세요.

**Server information/서버 정보**
1. Spigot/Paper/Bukkit/etc... version/사용중인 서버 버전
2. TriggerReactor version/사용중인 트리거 버전

**Error message/에러 메시지**
If error message (in red color) shows up in Minecraft client or on the console, report it here
에러메시지 (빨간색) 가 나타났다면 클라이언트와 콘솔의 메시지를 올려주세요.

**Others/그 밖의 정보들**
그 외의 다른 문제가 있으면 여기에 작성 해 주세요.

**Comment by rkdrns4747** [comment]
@Madur23 please tell us what's the purpose of this issue.

**Comment by rkdrns4747** [comment]
Unknown Issue. Closed.
