### ISSUE TITLE
Add PAPI phs support in our PAPI Expansion

### ISSUE THREAD

**Issue by rkdrns4747** [TriggerReactor/TriggerReactor#284]
As we know, our TR System's variable name can be created with path having username or uuid like:
`{"ticket."+player.getUniqueId()} = 3`

However, there's no way to put user information manually inside our PAPI Expansion when using it in other plugins because they don't know what $playername or $playeruuid is.
So, It would be great if we add support PH inside our PAPI Expansion, something like:
`%tr_ticket_{playername}%`
(automatically translate {playername} to %playername%, and get value from PAPI)

**Comment by wysohn** [comment]
I remember this is already done.

Please re-open if it's not

**Comment by rkdrns4747** [comment]
@wysohn exactly what this proposal means is adding PAPI support **inside** of our PAPI system that we already have done b4.
Since Global Variable can have personal data as a part of path (something like stats.**Dr_Romantic**.luck), We may need 2-layered PAPI to get the value of the variable properly.

I'm not gonna re-open this right now btw, I'll take this as soon as my whole college
