### ISSUE TITLE
Global Variable should be copied by cashed one, not from var.yml when it should be saved.

### ISSUE THREAD

**Issue by rkdrns4747** [TriggerReactor/TriggerReactor#289]
We have huge problem with Global Variable that **they does not saved in file directly when we sets one value in very short time like:
```
{"a.b.cccd"} = "hi" //saved in file
{"a.b.cccd"} = null //still value "hi" exists
```
why this is a significant problem is that if trigger plugin reloaded by `/trg reload` or disable simply by `/reload` or `/stop` , trigger saves value based on exist file, `var.yml`. though cashed, right value it has is different.
So, It should be fixed anyway, and I think it would be work saving cashed value to file once again before the plugin being reloaded/disabled.

**Comment by wysohn** [comment]
Is it the latest version?

**Comment by rkdrns4747** [comment]
Yes, I'm in 3.0.3

2020년 6월 14일 (일) 02:31, wysohn <notifications@github.com>님이 작성:

**Comment by wysohn** [comment]
Duplicate with #161

Will work on it
