### ISSUE TITLE
Command Error

### ISSUE THREAD

**Issue by chickiyeah** [TriggerReactor/TriggerReactor#314]
### **Before/읽어주세요**

Make sure that you have used `/trg debug` so that the more detailed error message will show up in the console.
신고전에 `/trg debug` 명령어를 사용해서 디버그 모드를 켜주세요. 그래야 콘솔창에 더 자세한 정보가 나옵니다.

---

**Describe the bug/버그 증상**
어떤 증상이 발상하는지 작성 해 주세요.

**Server information/서버 정보**
1. Spigot/Paper/Bukkit/etc... version/사용중인 서버 버전
2. TriggerReactor version/사용중인 트리거 버전

**Error message/에러 메시지**
If error message (in red color) shows up in Minecraft client or on the console, report it here
에러메시지 (빨간색) 가 나타났다면 클라이언트와 콘솔의 메시지를 올려주세요.

**Others/그 밖의 정보들**
그 외의 다른 문제가 있으면 여기에 작성 해 주세요.

Using /trg cmd in version 1.16.1 results in the same error as the image below
Plugin version in use : 3.0.5 latest
JAVA 1.8.0_251-b08
used buckkit : Spigot (Build with BuildTools) ![123456765432rttrew-2.png](https://user-images.githubusercontent.com/55694044/87458494-0bb9f200-c645-11ea-8c12-cbe7b55a54b8.png)![wqew.png](https://user-images.githubusercontent.com/55694044/87458550-1f655880-c645-11ea-881d-defd898fcf31.png)

**Comment by wysohn** [comment]
Probably fixed long long time ago.

The class that's causing NPE doesn't even exist in the latest version anymore.

Please re-open if the problem persist
