### ISSUE TITLE
#BROADCAST error in spigot mod server

### ISSUE THREAD

**Issue by sixtail1215** [TriggerReactor/TriggerReactor#377]
**How can i fix this bug XD anyone have answered?**
![image](https://user-images.githubusercontent.com/82817157/115236060-e0c17900-a155-11eb-8ff4-abcd96296844.png)

![image](https://user-images.githubusercontent.com/82817157/115236279-25e5ab00-a156-11eb-8831-e352180e7356.png)

**Comment by wysohn** [comment]
This is indeed a bug, and a fix will be released soon

#375

**Comment by wysohn** [comment]
@sixtail1215 
Wait, did you say Spigot mod server?

What's the type of server?
What version of Java are you using?
What version of TRG are you using?
