### ISSUE TITLE
WAIT can be used in SYNC block

### ISSUE THREAD

**Issue by wysohn** [TriggerReactor/TriggerReactor#411]
```
SYNC
#WAIT 123
ENDSYNC
```

This shouldn't be allowed as it will block the server thread

**Comment by soshimee** [comment]
I think it should, since it would be limiting users' abilities to lag the server (some people may purposefully want that in some very specific cases)

**Comment by wysohn** [comment]
> I think it should, since it would be limiting users' abilities to lag the server (some people may purposefully want that in some very specific cases)

Hmm I don't really see any application of lagging the server purposely.

Any examples?

It's true that it is constraining the user, but why would someone want to do it in the first place? Lagging the server not only wasting the resources but can trigger the watchdog thread to think the server is crashed, so it may end up terminating the server.

**Comment by Sayakie** [comment]
Seems had been resolved at #418 (for more context, see https://github.com/TriggerReactor/TriggerReactor/pull/418/commits/7f87f96eb4096f256e104d2d48eaee5c4e1ac5fa)
