### ISSUE TITLE
TriggerReactor's internal PAPI module is currently unavailable.

### ISSUE THREAD

**Issue by rkdrns4747** [TriggerReactor/TriggerReactor#413]
I'll look into it ASAP.

**Comment by wysohn** [comment]
In which version?

**Comment by rkdrns4747** [comment]
@wysohn It's pretty not sure right now. Only thing I can remember is that it's a bit ago from latest version, but still after refactoring, so 3.0.X or newer versions would have the problem.

**Comment by wysohn** [comment]
You have to make sure that which version it is happening

**Comment by rkdrns4747** [comment]
Looks like this is not a problem. Sorry for meaningless issue.
