### ISSUE TITLE
Adding set title function to InventoryTrigger

### ISSUE THREAD

**Issue by RookieAND** [TriggerReactor/TriggerReactor#416]
There's only one way to change inventory's title (by changing file's name) when InventoryTrigger has been called.
So I think it's better to add title option to set Inventory's title before InventoryTrigger is loaded.

**Comment by wysohn** [comment]
There seems to be a way to do this with the packets, yet it will have to send all the contents of the inventory again. 

https://www.spigotmc.org/threads/how-to-set-the-title-of-an-open-inventory-itemgui.95572/

maybe we can have good use of the protocollib support we have right now, so we can optionally support such function only when protocollib is available.

I would suggest doing this in Executor

**Comment by Ioloolo** [comment]
We can set the title of the inventory in the following ways:

```java
public IInventory openGUI(IPlayer player, String name) {
    InventoryTrigger trigger = get(name);
    if (trigger == null)
        return null;


                    /* Changed Part - START*/
    String title = trigger.getInfo().getConfig().get(TITLE, String.class).orElse(name);

    IInventory inventory = createInventory(trigger.getItems().length, title); 
                    /* Changed Part - END */


    inventoryMap.put(inventory, trigger);

    Map<String, Object> varMap = new HashMap<>();
    varMap.put("inventory", inventory.get());
    inventorySharedVars.put(inventory, varMap);

    fillInventory(trigger, trigger.getItems().length, inventory);

    player.openInventory(inventory);

    return inventory;
}
```

@wysohn

**Comment by wysohn** [comment]
> We can set the title of the inventory in the following ways:
> 
> ```java
> public IInventory openGUI(IPlayer player, String name) {
>     InventoryTrigger trigger = get(name);
>     if (trigger == null)
>         return null;
> 
> 
>                     /* Changed Part - START*/
>     String title = trigger.getInfo().getConfig().get(TITLE, String.class).orElse(name);
> 
>     IInventory inventory = createInventory(trigger.getItems().length, title); 
>                     /* Changed Part - END */
> 
> 
>     inventoryMap.put(inventory, trigger);
> 
>     Map<String, Object> varMap = new HashMap<>();
>     varMap.put("inventory", inventory.get());
>     inventorySharedVars.put(inventory, varMap);
> 
>     fillInventory(trigger, trigger.getItems().length, inventory);
> 
>     player.openInventory(inventory);
> 
>     return inventory;
> }
> ```
> 
> @wysohn

Looking good to me!

Why not open a PR for that? That would help all of us!

**Comment by Ioloolo** [comment]
It's simply because I didn't know how to use GitHub. I'm going to open a PR soon.

**Comment by RookieAND** [comment]
I truly appreciate to add this feature. I can't wait for it!

**Comment by wysohn** [comment]
> It's simply because I didn't know how to use GitHub. I'm going to open a PR soon.

Practice makes perfect

And neither I know everything about git. Google search is your friend :p
