### ISSUE TITLE
1.18 support

### ISSUE THREAD

**Issue by wysohn** [TriggerReactor/TriggerReactor#450]
It should work without any changes, but we still need to verify it before release.

**Comment by LimuLhw** [comment]
working on 1.18.1 Paper 136.
repeat Trigger is working, Negative Y Trigger(ex: Area, Click, Walk...) working.

**Comment by LimuLhw** [comment]
closed #450

**Comment by LimuLhw** [comment]
Trigger Reactor is working fine on real 1.18.1 server.
(When asking about 1.18.1 support in other people's QnA's, it seems that there were no compatibility issues other than JShader issues.)
