### ISSUE TITLE
Javascript Engine Manager not found in java 8

### ISSUE THREAD

**Issue by wysohn** [TriggerReactor/TriggerReactor#458]
OpenJDK Runtime Environment (build 1.8.0_312-8u312-b07-0ubuntu1~20.04-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)

**Comment by LimuLhw** [comment]
System Info: Java 1.8 (Java HotSpot(TM) 64-Bit Server VM 25.271-b09) Host: Windows 10 10.0 (amd64)
java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)

Tested on 3.3.0.5-Beta, Paper version git-Paper-792 (MC: 1.16.5)

**Comment by wysohn** [comment]
> System Info: Java 1.8 (Java HotSpot(TM) 64-Bit Server VM 25.271-b09) Host: Windows 10 10.0 (amd64) java version "1.8.0_271" Java(TM) SE Runtime Environment (build 1.8.0_271-b09) Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)
> 
> Tested on 3.3.0.5-Beta, Paper version git-Paper-792 (MC: 1.16.5)

@LimuLhw 
Thank you very much for the test!

But was it working or not working?

**Comment by LimuLhw** [comment]
@wysohn same happening and not working :(

**Comment by Sayakie** [comment]
At this moment, the issue does not reproduce and seems be resolved.
