### ISSUE TITLE
Inconsistent behavior of literal string "true"/"false"

### ISSUE THREAD

**Issue by Sayakie** [TriggerReactor/TriggerReactor#472]
# 🐛 Bug Report
The following example script code will be throw an exception that does not exist or parameter types not match. Because the variable `temp` would be parsed as Boolean type.
```cs
temp = "true"
FOR c = temp.getBytes()
  #MESSAGE c
ENDFOR
```

More examples below:
### Case 1.
Else branch never be executed.
```cs
temp = "true"
IF temp == true
  #MESSAGE "Wrong behavior! :("
ELSE
  #MESSAGE "We expected this behavior! :D"
ENDIF
```
![An example case 1 about this issue which prints only wrong behavior message](https://user-images.githubusercontent.com/18323202/155703246-6536a657-cf60-4786-9f0c-9c514dcdbb3c.png)

### Case 2.
Also else branch never be reached.
```cs
IMPORT java.lang.Boolean

IF "true" IS Boolean
  #MESSAGE "Wrong behavior! :("
ELSE
  #MESSAGE "We expected this behavior! :D"
ENDIF
```
![An example case 2 about this issue which prints only wrong behavior message](https://user-images.githubusercontent.com/18323202/155703246-6536a657-cf60-4786-9f0c-9c514dcdbb3c.png)

This behavior can lead to serious confusion later on.

### Test Environments
  * **Server Info**: CatServer 1.12.2 (Build based on Luohuayu/CatServer@a8b73e9)
  * **Minecraft Version**: 1.12.2
  * **TriggerReactor Version**: TriggerReactor Bukkit-legacy 3.3.0.6-beta

---
- See also: #471

**Comment by Sayakie** [comment]
https://github.com/TriggerReactor/TriggerReactor/blob/8e61dc8340cf92faeab00ac3fecd342d45e6c08a/core/src/main/java/io/github/wysohn/triggerreactor/core/script/parser/Parser.java#L904-L908

We must add Token type-check logic in order to make sure for Parser to work as intended.
```diff
--- if ("true".equals(token.value) || "false".equals(token.value)) { 
+++ if (token.type == Type.ID && ("true".equals(token.value) || "false".equals(token.value))) {
      Node node = new Node(new Token(Type.BOOLEAN, token.value, token.row, token.col)); 
      nextToken(); 
      return node; 
    } 
 ```
Reworked code will be parse literal string "true" as String type, not Boolean type.

**Comment by Sayakie** [comment]
@wysohn, I have a question, should we have to put this and #471 to `In progress` or `Beta`?

**Comment by wysohn** [comment]
> @wysohn, I have a question, should we have to put this and #471 to `In progress` or `Beta`?

I would say put the PR into the Beta and take #471 out of the board (and maybe close it)

**Comment by Sayakie** [comment]
Confirmed :D
