### ISSUE TITLE
Tab complete system is not designed correctly, remove tab hints

### ISSUE THREAD

**Issue by MidnightSugar** [TriggerReactor/TriggerReactor#481]
Right now, the tab complete uses a very odd system with hints and candidates that doesn't work very well at all. How tab complete is supposed to work, is you press tab to cycle through the different options and then, as you type it will filter out the options.

Right now when you press tab it just uses the command hint which doesn't make any sense.
As an example:

We have a command /warp <warpname> with options spawn, market and arena.
When people do /warp tab then the server will tell them the only available option for this command is trying to run "/warp \<warpname>". Tab complete will only work if players already know the warp names which defeats the purpose of tab complete.

How it should work is when they tab, they should get listed spawn, market, and arena. The idea of tab hint should be removed.

**Comment by wysohn** [comment]
This is already in progress #442
