### ISSUE TITLE
Door executors arguments broken

### ISSUE THREAD

**Issue by MidnightSugar** [TriggerReactor/TriggerReactor#484]
I tried DOOROPEN, DOORCLOSE, and DOORTOGGLE, and the arguments displayed on the wiki just throw errors.

It works using location() method though.
ReferenceError: "Location" is not defined

**Comment by wysohn** [comment]
> Also for the actual door mechanic, the doors sometimes don't open/close properly. Doors can be placed in 8 different directions, and how it opens depends on which direction the door is placed. Sometimes, this trigger messes up where the door is placed.

Do you have an example by any chance? The current implementation is quite simple in that it just picks up the door "block" and changes its state (either open or closed)

**Comment by rkdrns4747** [comment]
This bug will be handled in #486
