### ISSUE TITLE
TriggerReactor is not enabling in Paper-431 build

### ISSUE THREAD

**Issue by LimuLhw** [TriggerReactor/TriggerReactor#543]
**Describe the bug/버그 증상**
트리거 리액터가 버킷 빌드 업데이트 후 로드 안되는 현상.

**Server information/서버 정보**
1. Paper 1.19.3, 빌드 431, Java 17.0.6 OpenJDK
2. TriggerReactor 3.3.5, JShader 포함.

**Error message/에러 메시지**
![Screenshot_20230302_120522_Microsoft Remote Desktop](https://user-images.githubusercontent.com/6559842/222321274-c9feae87-b281-46e2-aebc-d817d78fd9bb.jpg)

**Others/그 밖의 정보들**
이전 Paper 빌드에서는 정상적으로 작동하였음.

**Comment by wysohn** [comment]
맨 위 로딩시에 뜨는 오류는 없었나요

**Comment by LimuLhw** [comment]
> 맨 위 로딩시에 뜨는 오류는 없었나요

![Screenshot_20230302_121138_Microsoft Remote Desktop](https://user-images.githubusercontent.com/6559842/222331337-791e21ed-769b-436a-a44f-95f5df508975.jpg)

**Comment by Sayakie** [comment]
Duplicate of #530

**Comment by Sayakie** [comment]
Similar to #530 but not the same issue
