### ISSUE TITLE
Event can't be cancelled for some third party plugins

### ISSUE THREAD

**Issue by wysohn** [TriggerReactor/TriggerReactor#545]
Event like [this](https://javadoc.jitpack.io/com/github/TownyAdvanced/Towny/0.98.4.0/javadoc/com/palmergames/bukkit/towny/event/PreNewTownEvent.html) is reported to be not cancelled even though #CANCELEVENT or event.setCancelled(true) is used.

Sync mode was true

Possibly because of the event priority but will need some investigation

**Comment by wysohn** [comment]
Could not reproduce.

Event is cancelled as intended.

![image](https://user-images.githubusercontent.com/8789836/227743248-67185dc0-54b9-4da0-aab4-40a777508ec9.png)

**Comment by Felleus** [comment]
I don't know... It doesn't work for me. But I'll try again today...

**Comment by wysohn** [comment]
> I don't know... It doesn't work for me. But I'll try again today...

Make sure that you have TriggerReactor and the other plugin that you are trying to test as other plugins may interfere
