### ISSUE TITLE
"Failed to rename temp file to Any_Trigger_name.json"

### ISSUE THREAD

**Issue by LimuLhw** [TriggerReactor/TriggerReactor#599]
**Describe the bug/버그 증상**
트리거 리액터를 활성화/비활성화/저장 및 리로드 시
Failed to rename temp file to Any_Trigger_name.json 가 뜹니다.
에리어 트리거, 커멘드, 커스텀 등등 모든 저장된 트리거 파일 json들이 표시됩니다.

![image](https://github.com/TriggerReactor/TriggerReactor/assets/6559842/6f20a310-f363-461b-be0c-b00ab3dfd8e3)

**Server information/서버 정보**
1. 1.20.1 Paper 최신 빌드, Java 17, Windows 10 22H2 환경
2. TriggerReactor 3.4.0.21 베타

**Error message/에러 메시지**
![image](https://github.com/TriggerReactor/TriggerReactor/assets/6559842/7c916d62-f2fb-43af-9cf7-04df4789a70d)

**Others/그 밖의 정보들**
=그 외 내용 없음=

**Comment by Sayakie** [comment]
Please post your full logs on paste.dev and comment the generated link inhere.

**Comment by wysohn** [comment]
일단 리눅스 환경에서는 문제가 없어서 윈도우에서도 또 테스트 해봐야겠네요

**Comment by LimuLhw** [comment]
> Please post your full logs on paste.dev and comment the generated link inhere.
3.4.0.22-Beta also not resolved this issue.
https://pastes.dev/SSuFAzrM8S

**Comment by LimuLhw** [comment]
https://pastes.dev/yN79KyXqwm
TRG 폴더 전부 초기화 한 다음, 커멘드 트리거 저장 및 리로드 시도해도 동일 증상이 나옵니다.
