### ISSUE TITLE
OnInteract 이벤트 관련

### ISSUE THREAD

**Issue by fadfhkdfga** [TriggerReactor/TriggerReactor#641]
### **Before/읽어주세요**

Make sure that you have used `/trg debug` so that the more detailed error message will show up in the console.
신고전에 `/trg debug` 명령어를 사용해서 디버그 모드를 켜주세요. 그래야 콘솔창에 더 자세한 정보가 나옵니다.

---
**Server information/서버 정보**

1. Spigot/Paper/Bukkit/etc... version/사용중인 서버 버전: Paper 1.20.4
2. TriggerReactor version/사용중인 트리거 버전: 3.4.7

Custom에 onInteract 이벤트를 추가하고 난 후, 플레이어가 블록을 길게 몇초간 우클릭하면 pps 제한 시스템들에 항상 걸립니다. (pps 제한을 많이 올려도 걸림)
onInteract 이벤트에서 블록을 길게 우클릭할 때 뭔가 많은? 일이 일어나는거 같은데 불가피한 현상인가요?
아니면 따로 이런 현상을 방지하는 방법이라도 있을까요?

**Comment by wysohn** [comment]
> ### **Before/읽어주세요**
> Make sure that you have used `/trg debug` so that the more detailed error message will show up in the console. 신고전에 `/trg debug` 명령어를 사용해서 디버그 모드를 켜주세요. 그래야 콘솔창에 더 자세한 정보가 나옵니다.
> 
> **Server information/서버 정보**
> 
> 1. Spigot/Paper/Bukkit/etc... version/사용중인 서버 버전: Paper 1.20.4
> 2. TriggerReactor version/사용중인 트리거 버전: 3.4.7
> 
> Custom에 onInteract 이벤트를 추가하고 난 후, 플레이어가 블록을 길게 몇초간 우클릭하면 pps 제한 시스템들에 항상 걸립니다. (pps 제한을 많이 올려도 걸림) onInteract 이벤트에서 블록을 길게 우클릭할 때 뭔가 많은? 일이 일어나는거 같은데 불가피한 현상인가요? 아니면 따로 이런 현상을 방지하는 방법이라도 있을까요?

pps 제한 시스템이 뭔가요?

onInteract의 경우 sync모드가 켜져있나요 혹시?

**Comment by fadfhkdfga** [comment]
초당 패킷 수 제한인데 Paper 등에 기본적으로 설정되어 있습니다. (디폴트 값으로 사용 중)

Sync true로 사용하고는 있는데 false에서도 상관 없이 발생합니다.

**Comment by wysohn** [comment]
> 초당 패킷 수 제한인데 Paper 등에 기본적으로 설정되어 있습니다. (디폴트 값으로 사용 중)
> 
> Sync true로 사용하고는 있는데 false에서도 상관 없이 발생합니다.

음 우클릭 할때 사용하는 트리거 코드가 뭔가요? 

패킷이 따로 더 늘어날만한 상황을 잘 모르겠네요
